import { Feather, Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { useSpace } from '@/context/SpaceContext';

export default function ListScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const router = useRouter(); const { activities } = useSpace();
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 110 }]} showsVerticalScrollIndicator={false}>
    <Text style={[styles.eyebrow, { color: colors.primary }]}>THE GOOD STUFF</Text><Text style={[styles.title, { color: colors.foreground }]}>Our list</Text><Text style={[styles.sub, { color: colors.mutedForeground }]}>Everything you want to experience together.</Text>
    <View style={[styles.summary, { backgroundColor: colors.secondary }]}><View><Text style={[styles.summaryNumber, { color: colors.foreground }]}>{activities.length}</Text><Text style={[styles.summaryLabel, { color: colors.mutedForeground }]}>ideas added</Text></View><View style={[styles.divider, { backgroundColor: colors.border }]} /><View><Text style={[styles.summaryNumber, { color: colors.primary }]}>{activities.filter((a) => a.status === 'Done').length}</Text><Text style={[styles.summaryLabel, { color: colors.mutedForeground }]}>completed</Text></View><View style={[styles.listIcon, { backgroundColor: colors.accent }]}><Ionicons name="sparkles-outline" size={22} color={colors.accentForeground} /></View></View>
    {activities.length === 0 ? <View style={[styles.empty, { borderColor: colors.border }]}><Ionicons name="compass-outline" size={30} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Your list starts here</Text><Text style={[styles.emptyCopy, { color: colors.mutedForeground }]}>What is something you have always wanted to try together?</Text><TouchableOpacity onPress={() => router.push('/add')} style={[styles.emptyButton, { backgroundColor: colors.foreground }]}><Text style={{ color: colors.background, fontWeight: '700' }}>Add your first idea</Text></TouchableOpacity></View> : activities.map((item) => <TouchableOpacity key={item.id} style={[styles.item, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.itemIcon, { backgroundColor: colors.secondary }]}><Ionicons name={item.status === 'Done' ? 'checkmark-circle' : 'compass-outline'} size={23} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.itemTitle, { color: colors.foreground }]}>{item.title}</Text><Text style={[styles.itemMeta, { color: colors.mutedForeground }]}>{item.category}  ·  {item.status}</Text></View><Feather name="more-horizontal" size={19} color={colors.mutedForeground} /></TouchableOpacity>)}
    <TouchableOpacity onPress={() => router.push('/add')} style={[styles.add, { borderColor: colors.border }]}><Ionicons name="add" size={19} color={colors.primary} /><Text style={[styles.addText, { color: colors.primary }]}>Add an idea</Text></TouchableOpacity>
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, gap: 12 }, eyebrow: { fontSize: 11, letterSpacing: 2, fontWeight: '700' }, title: { fontSize: 32, fontWeight: '700', letterSpacing: -1 }, sub: { fontSize: 14, marginBottom: 10 }, summary: { borderRadius: 20, padding: 17, flexDirection: 'row', alignItems: 'center', gap: 17, marginTop: 5 }, summaryNumber: { fontSize: 27, fontWeight: '700' }, summaryLabel: { fontSize: 11, marginTop: 1 }, divider: { width: 1, height: 38 }, listIcon: { marginLeft: 'auto', width: 44, height: 44, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, item: { borderWidth: 1, borderRadius: 20, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12 }, itemIcon: { width: 49, height: 49, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, itemTitle: { fontSize: 15, fontWeight: '600' }, itemMeta: { fontSize: 11, marginTop: 5 }, add: { height: 51, borderRadius: 17, borderWidth: 1, borderStyle: 'dashed', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, addText: { fontSize: 13, fontWeight: '700' }, empty: { borderWidth: 1, borderStyle: 'dashed', borderRadius: 22, minHeight: 240, alignItems: 'center', justifyContent: 'center', padding: 24, gap: 10 }, emptyTitle: { fontSize: 18, fontWeight: '700' }, emptyCopy: { fontSize: 13, textAlign: 'center', lineHeight: 19 }, emptyButton: { borderRadius: 15, paddingHorizontal: 16, paddingVertical: 13, marginTop: 5 } });