import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useColors } from '@/hooks/useColors';
import { useSpace } from '@/context/SpaceContext';

export default function ScoreScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const router = useRouter(); const { matches, yourName, partnerName } = useSpace();
  const youWins = matches.filter((match) => match.you > match.partner).length; const partnerWins = matches.filter((match) => match.partner > match.you).length;
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 110 }]}><Text style={[styles.eyebrow, { color: colors.primary }]}>A LITTLE FRIENDLY FIRE</Text><View style={styles.titleRow}><Text style={[styles.title, { color: colors.foreground }]}>Us vs Us</Text><View style={[styles.trophy, { backgroundColor: colors.secondary }]}><Ionicons name="trophy-outline" size={21} color={colors.primary} /></View></View><Text style={[styles.sub, { color: colors.mutedForeground }]}>Add every match and let the scoreboard tell the story.</Text><View style={[styles.champion, { backgroundColor: colors.foreground }]}><Text style={styles.champLabel}>OUR CHAMPIONSHIP</Text><Text style={styles.champText}>{matches.length ? (youWins === partnerWins ? 'It is perfectly even.' : `${youWins > partnerWins ? yourName || 'You' : partnerName || 'Partner'} is in the lead.`) : 'The first match is waiting.'}</Text><View style={styles.scoreRow}><View><Text style={styles.player}>{yourName || 'You'}</Text><Text style={styles.wins}>{youWins}<Text style={styles.winsLabel}> wins</Text></Text></View><Text style={styles.dash}>—</Text><View style={{ alignItems: 'flex-end' }}><Text style={styles.player}>{partnerName || 'Partner'}</Text><Text style={styles.wins}>{partnerWins}<Text style={styles.winsLabel}> wins</Text></Text></View></View></View><View style={styles.section}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Match history</Text><Text style={[styles.link, { color: colors.primary }]}>{matches.length} total</Text></View>{matches.length === 0 ? <View style={[styles.empty, { borderColor: colors.border }]}><Ionicons name="trophy-outline" size={29} color={colors.primary} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>No rivalry yet</Text><Text style={[styles.emptyCopy, { color: colors.mutedForeground }]}>Play something and settle the score.</Text></View> : matches.slice().reverse().map((match) => <View key={match.id} style={[styles.game, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.gameIcon, { backgroundColor: colors.secondary }]}><Ionicons name="game-controller-outline" size={21} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.gameTitle, { color: colors.foreground }]}>{match.game}</Text><Text style={[styles.gameMeta, { color: colors.mutedForeground }]}>{match.date}</Text></View><Text style={[styles.result, { color: colors.foreground }]}>{match.you} — {match.partner}</Text></View>)}<TouchableOpacity onPress={() => router.push('/add')} style={[styles.add, { borderColor: colors.border }]}><Ionicons name="add" size={18} color={colors.primary} /><Text style={[styles.addText, { color: colors.primary }]}>Add a match</Text></TouchableOpacity></ScrollView>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 20, gap: 12 }, eyebrow: { fontSize: 11, letterSpacing: 2, fontWeight: '700' }, titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontSize: 32, fontWeight: '700', letterSpacing: -1 }, trophy: { width: 45, height: 45, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, sub: { fontSize: 14 }, champion: { borderRadius: 23, padding: 19, marginTop: 7 }, champLabel: { color: '#D6B7B0', fontSize: 10, letterSpacing: 1.5, fontWeight: '700' }, champText: { color: '#F8E8E0', fontSize: 17, fontWeight: '600', marginTop: 13 }, scoreRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: 22 }, player: { color: '#C7AEB0', fontSize: 12 }, wins: { color: '#FFF8F1', fontSize: 33, fontWeight: '700', marginTop: 3 }, winsLabel: { color: '#C7AEB0', fontSize: 12, fontWeight: '500' }, dash: { color: '#9C7F87', fontSize: 23, marginBottom: 8 }, section: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 11 }, sectionTitle: { fontSize: 18, fontWeight: '700' }, link: { fontSize: 12, fontWeight: '600' }, game: { borderWidth: 1, borderRadius: 19, padding: 12, flexDirection: 'row', gap: 11, alignItems: 'center' }, gameIcon: { width: 45, height: 45, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, gameTitle: { fontSize: 15, fontWeight: '700' }, gameMeta: { fontSize: 11, marginTop: 4 }, result: { fontSize: 15, fontWeight: '700' }, add: { height: 51, borderRadius: 17, borderWidth: 1, borderStyle: 'dashed', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, addText: { fontSize: 13, fontWeight: '700' }, empty: { borderWidth: 1, borderStyle: 'dashed', borderRadius: 22, minHeight: 190, alignItems: 'center', justifyContent: 'center', padding: 22, gap: 9 }, emptyTitle: { fontSize: 17, fontWeight: '700' }, emptyCopy: { textAlign: 'center', fontSize: 13 } });